extends SceneTree

## Headless smoke test. Run:
##   godot --headless --path . --script res://_selftest.gd
##
## Checks that every script compiles (see _all_scripts()) and sanity-checks the
## project config (portrait canvas, stretch mode, input map incl. device -1 on
## every joypad binding — RG552).

## Every game script, found automatically — a hand-kept list silently goes
## stale. Walks res:// recursively, skipping addons/, tools/, android/ (Godot's
## build template), hidden and .gdignore'd folders and _-prefixed dev scripts
## (_selftest.gd itself, local helpers like _capture.gd).
## A script only counts if it also COMPILES: in Godot 4 load() returns the
## resource even when compilation failed (incl. a broken dependency), so check
## can_instantiate() (found in mario-clone v1.1, where `load() != null` let a
## type-inference error through with "all checks passed" and exit 0).
const SKIP_DIRS := ["addons", "tools", "android"]

func _all_scripts(dir := "res://") -> Array[String]:
	var out: Array[String] = []
	for f in DirAccess.get_files_at(dir):
		if f.ends_with(".gd") and not f.begins_with("_"):
			out.append(dir.path_join(f))
	for d in DirAccess.get_directories_at(dir):
		var sub := dir.path_join(d)
		if d.begins_with(".") or d in SKIP_DIRS or FileAccess.file_exists(sub.path_join(".gdignore")):
			continue
		out.append_array(_all_scripts(sub))
	return out

func _init() -> void:
	var fails := 0

	var scripts := _all_scripts()
	fails += _expect(scripts.size() >= 9, "found %d scripts (expect >= 9)" % scripts.size())
	for path in scripts:
		var s: Script = load(path)
		fails += _expect(s != null and s.can_instantiate(), "compiles: %s" % path)

	# --- project config -----------------------------------------------------
	var canvas := Vector2(
		ProjectSettings.get_setting("display/window/size/viewport_width"),
		ProjectSettings.get_setting("display/window/size/viewport_height"))
	fails += _expect(canvas.y > canvas.x, "design canvas is portrait (%dx%d)" % [canvas.x, canvas.y])
	fails += _expect(ProjectSettings.get_setting("display/window/stretch/mode") == "canvas_items",
		"stretch mode = canvas_items")
	for action in ["move_up", "move_down", "move_left", "move_right", "pause", "ui_accept", "ui_cancel"]:
		fails += _expect(InputMap.has_action(action), "input action present: %s" % action)
	for action in InputMap.get_actions():
		for e in InputMap.action_get_events(action):
			if (e is InputEventJoypadButton or e is InputEventJoypadMotion) and e.device != -1:
				fails += _expect(false, "joypad binding of %s uses device -1 (has %d)" % [action, e.device])

	# --- mazes (maze_data.gd, generated by tools/make_mazes.py) ----------------
	for i in MazeGrid.maze_count():
		MazeGrid.set_maze(i)
		fails += _check_maze(i)
	MazeGrid.set_maze(0)
	for lvl in [1, 2, 3, 5, 6, 9, 10, 13, 14, 18, 99]:
		var mi := MazeGrid.maze_for_level(lvl)
		fails += _expect(mi >= 0 and mi < MazeGrid.maze_count(), "maze_for_level(%d) = %d in range" % [lvl, mi])

	if fails == 0:
		print("_selftest: all checks passed")
	else:
		printerr("_selftest: %d check(s) FAILED" % fails)
	quit(1 if fails > 0 else 0)

func _expect(cond: bool, label: String) -> int:
	if cond:
		print("  ok  ", label)
		return 0
	printerr("  FAIL ", label)
	return 1


## Every free cell reachable (side tunnel wraps), power pills + start strip +
## house interior free, no dead ends, no 2x2 open areas outside the house band.
func _check_maze(i: int) -> int:
	var f := 0
	var free_cells: Array[Vector2i] = []
	for y in MazeGrid.ROWS:
		for x in MazeGrid.COLS:
			if MazeGrid.is_free(Vector2i(x, y)):
				free_cells.append(Vector2i(x, y))
	var seen := {free_cells[0]: true}
	var queue: Array[Vector2i] = [free_cells[0]]
	var head := 0
	while head < queue.size():
		var c: Vector2i = queue[head]
		head += 1
		for d in [Vector2i.UP, Vector2i.DOWN, Vector2i.LEFT, Vector2i.RIGHT]:
			var n: Vector2i = c + d
			if MazeGrid.is_tunnel_exit(c, d):
				n = Vector2i(MazeGrid.COLS - 1, c.y) if d == Vector2i.LEFT else Vector2i(0, c.y)
			if MazeGrid.is_free(n) and not seen.has(n):
				seen[n] = true
				queue.append(n)
	f += _expect(seen.size() == free_cells.size(), "maze %d: all %d free cells reachable" % [i, free_cells.size()])
	for cell in MazeGrid.BIG_PILLS:
		f += _expect(MazeGrid.is_free(cell), "maze %d: power pill cell %s free" % [i, cell])
	for cell in [Vector2i(14, 22), Vector2i(15, 22), Vector2i(14, 11), Vector2i(15, 11), Vector2i(13, 10), Vector2i(16, 10)]:
		f += _expect(MazeGrid.is_free(cell), "maze %d: fixed cell %s free" % [i, cell])
	var dead := 0
	for c in free_cells:
		if c.y == 13 and (c.x == 0 or c.x == MazeGrid.COLS - 1):
			continue
		var n := 0
		for d in [Vector2i.UP, Vector2i.DOWN, Vector2i.LEFT, Vector2i.RIGHT]:
			if MazeGrid.is_free(c + d):
				n += 1
		if n <= 1:
			dead += 1
	f += _expect(dead == 0, "maze %d: no dead ends (%d)" % [i, dead])
	f += _expect(MazeGrid.build_pills().size() > 150, "maze %d: pill count %d" % [i, MazeGrid.build_pills().size()])
	return f
