#!/usr/bin/env python3
"""Regenerates assets/ for the architecture dossier from its real sources.

Run from this directory: python3 prepare_assets.py

What's reproducible from files already in this repo:
  - fig-scenetree.png / fig-ghost-fsm.png  <- rendered here from diagrams/*.dot
    (Graphviz; `dot` must be on PATH)
  - fig-controls.png                       <- copied straight from the game's
    own help illustration (assets/graphics/help/keyboard.png)
  - pacman-icon.png                        <- copied from the app's own
    launcher icon (pacman-icon 432x432.png in the project root)

What ISN'T reproducible by this script (kept only as the already-captured
files already sitting in assets/ - this script leaves them alone):
  - fig-chase.jpg / fig-frightened.jpg — real in-game screenshots captured
    live via a throwaway `_capture.gd`/`_capture.tscn` scene (loads
    pacman_map.tscn, calls settings.request_play(), waits for Blinky/Pinky
    to leave and chase, then calls game._start_frightened() directly for the
    second shot) during the 2026-09-16 session, then downscaled to 960px
    wide / JPEG q85. Recapturing needs that scene run with a real DISPLAY
    (`godot --path . res://_capture.tscn -- <out_dir>`, not --headless); the
    capture script itself is a throwaway and is not committed. Nothing to
    "run" here without recreating it first.
"""

import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACMAN_ROOT = HERE.parent.parent
ASSETS = HERE / "assets"
DIAGRAMS = HERE / "diagrams"

ASSETS.mkdir(exist_ok=True)


def render_diagram(dot_file: Path, out_file: Path, dpi: int = 150) -> None:
    subprocess.run(
        ["dot", "-Tpng", f"-Gdpi={dpi}", str(dot_file), "-o", str(out_file)],
        check=True,
    )
    print("rendered", out_file.relative_to(HERE))


def copy_asset(src: Path, dst: Path) -> None:
    shutil.copyfile(src, dst)
    print("copied", dst.relative_to(HERE), "<-", src)


def main() -> None:
    render_diagram(DIAGRAMS / "scenetree.dot", ASSETS / "fig-scenetree.png")
    render_diagram(DIAGRAMS / "ghost_fsm.dot", ASSETS / "fig-ghost-fsm.png")

    copy_asset(
        PACMAN_ROOT / "assets" / "graphics" / "help" / "keyboard.png",
        ASSETS / "fig-controls.png",
    )
    copy_asset(
        PACMAN_ROOT / "pacman-icon 432x432.png",
        ASSETS / "pacman-icon.png",
    )

    print(
        "\nfig-chase.jpg / fig-frightened.jpg left untouched - real captured "
        "in-game screenshots, not regenerated by this script (see the "
        "module docstring)."
    )


if __name__ == "__main__":
    main()
